### ISSUE TITLE
objectPropertys 函数

### ISSUE THREAD

**Issue by malaimoo** [lijingcheng/FMDBHelper#1]
大神：
NSObject+JCAdditionsORM.m 里面，这个函数是啥情况呢？返回的是空字典？
- (NSDictionary *)objectPropertys
  {
  return @{};
  }

**Comment by lijingcheng** [comment]
@malaimoo 如果你用自己定义的类做为Model类的属性类型，那么需要在Model类中重写“ objectPropertys”方法，具体做法在demo里有，“NSObject+JCAdditionsORM.m”中这个方法返回@{}，是假设你的Model类中包含的属性没有自定义类型
