### ISSUE TITLE
dbPath能开放出来配置就好了

### ISSUE THREAD

**Issue by ap0806109** [lijingcheng/FMDBHelper#2]
弄个setDBPath

**Comment by lijingcheng** [comment]
@ap0806109 因为考虑到数据库文件只能放在documents目录下，所以没有开放接口方法，如果你的数据库是通过代码创建，而不是放在bundle中的数据库文件，那么可以先在documents中创建数据库，然后再调用“setDataBaseName”方法设置下名字就可以了

**Comment by ap0806109** [comment]
@lijingcheng  我现在遇到的问题就是 系统创建的db文件不是放在documents的根目录下，下面还有子目录，这样的话 用这个helper就没法读取到

**Comment by lijingcheng** [comment]
@ap0806109 之前没考虑到db会放到documents的子目录下，我感觉大多数应用都会直接放根目录下吧，FMDBHelper设计时考虑的就是代码及api能尽最大可能简单些，支持绝大数情况就可以，所以从这个角度上我还是不太想开放 setDBPath方法，不过我觉得你这边可以fork后，自己改一下，或者考虑下db放在documents的子目录下是否有必要
