### ISSUE TITLE
ID 不应该加在 insertObject 里面

### ISSUE THREAD

**Issue by harde1** [lijingcheng/FMDBHelper#3]
![1](https://cloud.githubusercontent.com/assets/7310921/18857537/4e1a672c-8497-11e6-9133-dbcbe6a343c3.png)
insert 应该会新的，ID会导致不行

**Comment by lijingcheng** [comment]
@harde1 不行是因为主键重复，所以insert失败啊，有啥问题吗？

**Comment by harde1** [comment]
insert一个新的值，主键默认为 nil,不给 ID赋值，会导致不能 insert，还有自增值，怎么操作？

**Comment by lijingcheng** [comment]
@harde1 如果主键是自增长字段，那么就不需要给主键id赋值，如果主键不是自增长字段，那么他应该设计成非空的字段，另外FMDBHelper里将主键写死为“id"了，所以如果你的主键不叫这个名字，那么你可以fork后自己改下“NSObject+JCAdditionsORM”文件中的“identifier”

**Comment by lijingcheng** [comment]
@harde1 另外主键为nil，导致不能insert，我觉得这没啥问题啊，你做好异常处理就行了，insert方法会返回bool值，告诉你是否insert成功
